# Generated by Django 3.2.3 on 2021-06-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repere',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
